### ISSUE TITLE
Endpoints with `Put` verbs not processed at all

### ISSUE THREAD

**Issue by oishikg** [Holmusk/servant-docs-simple#18]
We have added a new API endpoint with a `PUT` verb to the spec. Unfortunately, on attempting to generate the documentation, no documentation is generated for the `PUT` endpoint.

**Comment by turboMaCk** [comment]
@jhrcek any idea why is this? Also most likely the situation will be same for `PATCH` method which is also quite common and useful.

**Comment by jhrcek** [comment]
No idea yet.
I expanded tests to include endpoints with other verbs, but it seems to be working.
@oishikg when you have a minute could you point me to the code where it's not working for you?
If it's company private code, just sent it to me via teams chat..

**Comment by jhrcek** [comment]
Resolved in https://github.com/Holmusk/servant-docs-simple/pull/21
